name: very_good_analysis
version: 5.1.0
description: Lint rules for Dart and Flutter used internally at Very Good Ventures.
repository: https://github.com/VeryGoodOpenSource/very_good_analysis
issue_tracker: https://github.com/VeryGoodOpenSource/very_good_analysis/issues
homepage: https://github.com/VeryGoodOpenSource/very_good_analysis
documentation: https://github.com/VeryGoodOpenSource/very_good_analysis

environment:
  sdk: ">=3.0.0 <4.0.0"
